### ISSUE TITLE
Not able to implement in Nextjs - resolvePath is not a function

### ISSUE THREAD

**Issue by kouliavtsev** [ksoichiro/rehype-img-size#1]
Implemented based on [How to use Next.js Image with Markdown (or MDX!)](https://ironeko.com/posts/how-to-use-next-js-image-with-markdown-or-mdx)

**Image**
`/public/image.png`

**Markdown**
```
![](/public/image.png)
```

**getStaticProps**
```
  const mdxSource = await serialize(content, {
    mdxOptions: {
      rehypePlugins: [[imageSize, { dir: "public" }]],
    },
  });
```

The path does not seem to resolve... Tried to update the dir to `public/images`. I wonder if there is a good way to check what path is being used under the hood?

**Comment by kouliavtsev** [comment]
Solved: It was related to the article path, not images. :)

**Comment by whexy** [comment]
> Solved: It was related to the article path, not images. :)

Would you please explain what that means? I encounter the same problem and don't know how to fix it.

**Comment by antoniojps** [comment]
Same issue here @kouliavtsev can you share how you fixed this?

**Comment by kouliavtsev** [comment]
@whexy @antoniojps The issue I had, not sure if this is related to you was due to the import path being incorrect.

`import imageSize from "../../image-size";`

Hope this helps

**Comment by Xananax** [comment]
What you need to do:

1. uninstall `rehype-image-size`
2. `npm i --save ksoichiro/rehype-img-size`

The latest module is not published on npm yet

**Comment by wangpin34** [comment]
> What you need to do:
> 
> 1. uninstall `rehype-image-size`
> 2. `npm i --save ksoichiro/rehype-img-size`
> 
> The latest module is not published on npm yet

Save my day! `v1.0.1` does resolve the issue.

**Comment by rexfordessilfie** [comment]
I experienced a similar error recently. I am Next.js 13.4.4 (App Router).
* The options `{dir: "public"}` worked locally, and when deployed and page was rendered through Static-Site Generation.
* It didn't work when trying to use  it in Server-Side Rendering or with Next.js' `revalidatePath`
* The reason it broke was it was trying to load an image from `var/task/public/<path-to-the-image>`, and could not find the file there
    * Side Note: the error message was very cryptic with no indication that it could be coming from rehype. It would be great if the library could catch and re-throw a more meaningful error message 🙂 
  
THE FIX:
* According to this Stack Overflow [post](https://stackoverflow.com/a/65861629/13944042), use `process.cwd()` for `dir` since the MDX is being loaded in an SSR context. 
* Specifically this is what I had:

```js
const rehypeImgSizeDir = `${process.cwd()}/public`;

export const mdxOptions = {
  rehypePlugins: [[rehypeImgSize, { dir: rehypeImgSizeDir }]],
};
```
